// AUTO-GENERATED by scripts/generate-placeholders.mjs — do not edit by hand.
// Re-run `npm run placeholders` after replacing any image in public/images/.

export type ImageSlot = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  alt: string;
};

export const images = {
  "heroSafariJumpMurram": {
    src: "/images/hero-safari-jump-murram-1320x1132.jpg",
    width: 1320,
    height: 1132,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAHBAAAgEFAQAAAAAAAAAAAAAAAQIAAwQREiEx/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABsRAAIBBQAAAAAAAAAAAAAAAAABAgMREyFB/9oADAMBAAIRAxEAPwABEOwyORu3uRTohZmUDHgkX40Mqr4Kwxts/9k=",
    alt: "Safari rally car, competition number 26, airborne over a murram crest, red dust trailing, East African bush behind",
  },
  "drive01ArrivalNairobi": {
    src: "/images/drive-01-arrival-nairobi-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAHBAAAQUAAwAAAAAAAAAAAAAAAAECAwQSEzFB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDKrWnVY8tXsl0nIul9AIP/2Q==",
    alt: "The Safari-prepared 911 among the support vehicles at the base on arrival day",
  },
  "drive02ShakedownTest": {
    src: "/images/drive-02-shakedown-test-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGBABAQADAAAAAAAAAAAAAAAAAQACETH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwDIZicqLqSRa//Z",
    alt: "The Safari car at speed in side profile on a test road, driver visible at the wheel",
  },
  "drive03ReadyToStart": {
    src: "/images/drive-03-ready-to-start-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAGRAAAwADAAAAAAAAAAAAAAAAAAECAxEh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAIRMf/aAAwDAQACEQMRAD8AxIm7fWWxj1KTAAbuyhocn//Z",
    alt: "Driver helmeted and strapped in behind the roll cage, waiting for the off",
  },
  "drive04TheEvent": {
    src: "/images/drive-04-the-event-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAID/8QAGxAAAgEFAAAAAAAAAAAAAAAAAAECAwQRElH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AxdzUS0bJzPoADf/Z",
    alt: "The competition car on murram between the thorn trees, dust rising behind",
  },
  "drive05FinishRamp": {
    src: "/images/drive-05-finish-ramp-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGxAAAgIDAQAAAAAAAAAAAAAAAAECAwQRIRP/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEQMRAD8At2L5db2jPtnBTfAAqsv/2Q==",
    alt: "The crew going over the car at the end of the day, spare wheel out, everyone around the back of the car",
  },
  "peopleCrewAtWork": {
    src: "/images/people-crew-at-work-900x1125.jpg",
    width: 900,
    height: 1125,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAGhAAAgMBAQAAAAAAAAAAAAAAAQIAAwQRMf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Agy6Ato5GVtcqCBMtksJtEbXVYqgDyQf/2Q==",
    alt: "Minti crew in team shirts working over the car at service",
  },
  "peopleWorkshopNairobi": {
    src: "/images/people-workshop-nairobi-900x1125.jpg",
    width: 900,
    height: 1125,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAwDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMFBv/EABkQAAMBAQEAAAAAAAAAAAAAAAECEQADBP/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8AyoViKMQ6dFEuovxTmYoyT56bjUWU0f/Z",
    alt: "Freshly built air-cooled engine in the bay, twin carburettors, spotless",
  },
  "askMurramRoadAerial": {
    src: "/images/ask-murram-road-aerial-2400x1200.jpg",
    width: 2400,
    height: 1200,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAGAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAGxAAAgIDAQAAAAAAAAAAAAAAAAECBQMEMTL/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8AyK42JLpGVnnb9MAl0j//2Q==",
    alt: "Aerial view of a murram road running dead straight through the bush to the horizon",
  },
  "driveHeroCockpit": {
    src: "/images/drive-hero-cockpit-2400x1350.jpg",
    width: 2400,
    height: 1350,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEG/8QAGRAAAwADAAAAAAAAAAAAAAAAAAIRAQMh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8AzbS8Kum4oALlf//Z",
    alt: "Period cockpit gauges up close, speedometer sweep and tachometer needle of the Safari car",
  },
  "carsMk1MountainRoad": {
    src: "/images/cars-mk1-mountain-road-1299x1047.jpg",
    width: 1299,
    height: 1047,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAHRAAAgEEAwAAAAAAAAAAAAAAAAIBAwURFTEyQf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwCmuLU1zMh7dvDOfqHHAVMf/9k=",
    alt: "Red Ford Escort Mk1 rally build on a wet mountain pass, gold wheels, roll cage visible through the glass",
  },
  "carsMk2GoldMinilites": {
    src: "/images/cars-mk2-gold-minilites-800x538.jpg",
    width: 800,
    height: 538,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAIAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAGRAAAgMBAAAAAAAAAAAAAAAAAAIBBBED/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAAgH/2gAMAwEAAhEDEQA/AJJU61X1YNitZaN2QBrUy//Z",
    alt: "Escort Mk2 rally build in blue with gold Minilite-style wheels and Cibie spotlamps outside the workshop",
  },
  "carsBuildMstWorkshop": {
    src: "/images/cars-build-mst-workshop-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGxAAAQQDAAAAAAAAAAAAAAAAAAECAzESFEH/xAAVAQEBAAAAAAAAAAAAAAAAAAACBP/EABYRAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEQMRAD8AyRsfMmK2XSTtgAUzMf/Z",
    alt: "A mechanic's hand on the welded-in roll cage of the red Safari build",
  },
  "carsCockpitDetail": {
    src: "/images/cars-cockpit-detail-1200x1500.jpg",
    width: 1200,
    height: 1500,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAPAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEG/8QAGRABAAMBAQAAAAAAAAAAAAAAAQACESED/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQP/xAAYEQACAwAAAAAAAAAAAAAAAAAAEQECEv/aAAwDAQACEQMRAD8AzVKj1h2wtEBDJTw3sHBTNmf/2Q==",
    alt: "Cockpit gauges up close, tachometer needle and speedometer of the Safari car",
  },
  "teamCrewWorking": {
    src: "/images/team-crew-working-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAaEAACAgMAAAAAAAAAAAAAAAAAAQMEAhIT/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCTVuPqi/FLtgmABj//2Q==",
    alt: "Minti crew in team shirts over the car under the carport at service",
  },
  "teamCrewService": {
    src: "/images/team-crew-service-2400x1350.jpg",
    width: 2400,
    height: 1350,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAZEAADAQEBAAAAAAAAAAAAAAAAAQIDEQT/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCCvNcPpbjPc02wAsf/2Q==",
    alt: "Minti crew in team shirts around the car at service",
  },
  "teamWorkshopBay": {
    src: "/images/team-workshop-bay-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGxAAAwACAwAAAAAAAAAAAAAAAAECAwQFETH/xAAVAQEBAAAAAAAAAAAAAAAAAAACBP/EABYRAQEBAAAAAAAAAAAAAAAAAAACAf/aAAwDAQACEQMRAD8AxNrVdW7p+kx8fVz2mAFRM4//2Q==",
    alt: "Freshly built air-cooled engine in the bay, twin carburettors, spotless",
  },
  "heritageMintiStageBw": {
    src: "/images/heritage-minti-stage-bw-1320x868.jpg",
    width: 1320,
    height: 868,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAIAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAZEAADAQEBAAAAAAAAAAAAAAAAAQIEAxH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AqzaU+Pk0S9NSVtOgAP/Z",
    alt: "Archive black-and-white photograph: Minti-liveried classic rally saloon at speed on an East African stage, panned through thorn scrub",
  },
  "journalServiceParkCraft": {
    src: "/images/journal-service-park-craft-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEF/8QAGBAAAwEBAAAAAAAAAAAAAAAAAAECAyH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwCb05wZmLap4AFtf//Z",
    alt: "Gloved hands on the wheel nuts mid wheel-change, close up",
  },
  "journalWhyTheEscort": {
    src: "/images/journal-why-the-escort-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAbEAABBAMAAAAAAAAAAAAAAAAAAQIDIQQRFP/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAEx/9oADAMBAAIRAxEAPwCMmUsTKI98i3sALmP/2Q==",
    alt: "Red Ford Escort Mk1 rally build on a mountain road",
  },
  "journalReadingTheRoad": {
    src: "/images/journal-reading-the-road-1600x1000.jpg",
    width: 1600,
    height: 1000,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAwDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAZEAACAwEAAAAAAAAAAAAAAAAAAQMFEQL/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwCLupmibspunugBWMR//9k=",
    alt: "Aerial of a murram road cutting through acacia scrub",
  },
  "ogDefault": {
    src: "/images/og-default-1200x630.jpg",
    width: 1200,
    height: 630,
    blurDataURL: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAGAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGhAAAgIDAAAAAAAAAAAAAAAAAAECAxEhMv/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDI1NY2icumAB//2Q==",
    alt: "Minti Motorsport, Preserving Heritage",
  },
} as const satisfies Record<string, ImageSlot>;
